// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/plugins/grpc/sessions/proto/sessions.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Committed     bool                   `protobuf:"varint,3,opt,name=committed,proto3" json:"committed,omitempty"`
	Archived      bool                   `protobuf:"varint,4,opt,name=archived,proto3" json:"archived,omitempty"`
	MessageCount  int32                  `protobuf:"varint,5,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionProto) Reset() {
	*x = SessionProto{}
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionProto) ProtoMessage() {}

func (x *SessionProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionProto.ProtoReflect.Descriptor instead.
func (*SessionProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP(), []int{0}
}

func (x *SessionProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionProto) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *SessionProto) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

func (x *SessionProto) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *SessionProto) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *SessionProto) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MessageProto struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId         string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Role              string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Content           string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ToolCalls         []*ToolCallProto       `protobuf:"bytes,5,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	CreatedAtUnixNano int64                  `protobuf:"varint,6,opt,name=created_at_unix_nano,json=createdAtUnixNano,proto3" json:"created_at_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MessageProto) Reset() {
	*x = MessageProto{}
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageProto) ProtoMessage() {}

func (x *MessageProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageProto.ProtoReflect.Descriptor instead.
func (*MessageProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP(), []int{1}
}

func (x *MessageProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageProto) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MessageProto) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MessageProto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageProto) GetToolCalls() []*ToolCallProto {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *MessageProto) GetCreatedAtUnixNano() int64 {
	if x != nil {
		return x.CreatedAtUnixNano
	}
	return 0
}

type ToolCallProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     *structpb.Struct       `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	IsError       bool                   `protobuf:"varint,5,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallProto) Reset() {
	*x = ToolCallProto{}
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallProto) ProtoMessage() {}

func (x *ToolCallProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallProto.ProtoReflect.Descriptor instead.
func (*ToolCallProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP(), []int{2}
}

func (x *ToolCallProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCallProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCallProto) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ToolCallProto) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolCallProto) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        string                 `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSessionRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateSessionRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP(), []int{4}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP(), []int{5}
}

func (x *ListSessionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionProto        `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP(), []int{6}
}

func (x *ListSessionsResponse) GetSessions() []*SessionProto {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CommitSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitSessionRequest) Reset() {
	*x = CommitSessionRequest{}
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitSessionRequest) ProtoMessage() {}

func (x *CommitSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitSessionRequest.ProtoReflect.Descriptor instead.
func (*CommitSessionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP(), []int{8}
}

func (x *CommitSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AddMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       *MessageProto          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMessageRequest) Reset() {
	*x = AddMessageRequest{}
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMessageRequest) ProtoMessage() {}

func (x *AddMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMessageRequest.ProtoReflect.Descriptor instead.
func (*AddMessageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP(), []int{9}
}

func (x *AddMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddMessageRequest) GetMessage() *MessageProto {
	if x != nil {
		return x.Message
	}
	return nil
}

type GetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP(), []int{10}
}

func (x *GetMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type ListMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP(), []int{11}
}

func (x *ListMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListMessagesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*MessageProto        `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP(), []int{12}
}

func (x *ListMessagesResponse) GetMessages() []*MessageProto {
	if x != nil {
		return x.Messages
	}
	return nil
}

type CountMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountMessagesRequest) Reset() {
	*x = CountMessagesRequest{}
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountMessagesRequest) ProtoMessage() {}

func (x *CountMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountMessagesRequest.ProtoReflect.Descriptor instead.
func (*CountMessagesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP(), []int{13}
}

func (x *CountMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CompactMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactMessagesRequest) Reset() {
	*x = CompactMessagesRequest{}
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactMessagesRequest) ProtoMessage() {}

func (x *CompactMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactMessagesRequest.ProtoReflect.Descriptor instead.
func (*CompactMessagesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP(), []int{14}
}

func (x *CompactMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type BoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolResponse) Reset() {
	*x = BoolResponse{}
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolResponse) ProtoMessage() {}

func (x *BoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolResponse.ProtoReflect.Descriptor instead.
func (*BoolResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP(), []int{15}
}

func (x *BoolResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP(), []int{16}
}

func (x *CountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CompactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       int32                  `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactResponse) Reset() {
	*x = CompactResponse{}
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactResponse) ProtoMessage() {}

func (x *CompactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactResponse.ProtoReflect.Descriptor instead.
func (*CompactResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP(), []int{17}
}

func (x *CompactResponse) GetRemoved() int32 {
	if x != nil {
		return x.Removed
	}
	return 0
}

var File_pkg_plugins_grpc_sessions_proto_sessions_proto protoreflect.FileDescriptor

const file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDesc = "" +
	"\n" +
	".pkg/plugins/grpc/sessions/proto/sessions.proto\x12\bsessions\x1a\x1cgoogle/protobuf/struct.proto\"\xca\x01\n" +
	"\fSessionProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x1c\n" +
	"\tcommitted\x18\x03 \x01(\bR\tcommitted\x12\x1a\n" +
	"\barchived\x18\x04 \x01(\bR\barchived\x12#\n" +
	"\rmessage_count\x18\x05 \x01(\x05R\fmessageCount\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xd4\x01\n" +
	"\fMessageProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x126\n" +
	"\n" +
	"tool_calls\x18\x05 \x03(\v2\x17.sessions.ToolCallProtoR\ttoolCalls\x12/\n" +
	"\x14created_at_unix_nano\x18\x06 \x01(\x03R\x11createdAtUnixNano\"\x9d\x01\n" +
	"\rToolCallProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\targuments\x18\x03 \x01(\v2\x17.google.protobuf.StructR\targuments\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12\x19\n" +
	"\bis_error\x18\x05 \x01(\bR\aisError\"c\n" +
	"\x14CreateSessionRequest\x12\x16\n" +
	"\x06author\x18\x01 \x01(\tR\x06author\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"C\n" +
	"\x13ListSessionsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"J\n" +
	"\x14ListSessionsResponse\x122\n" +
	"\bsessions\x18\x01 \x03(\v2\x16.sessions.SessionProtoR\bsessions\"5\n" +
	"\x14DeleteSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"5\n" +
	"\x14CommitSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"d\n" +
	"\x11AddMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x120\n" +
	"\amessage\x18\x02 \x01(\v2\x16.sessions.MessageProtoR\amessage\"Q\n" +
	"\x11GetMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"b\n" +
	"\x13ListMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"J\n" +
	"\x14ListMessagesResponse\x122\n" +
	"\bmessages\x18\x01 \x03(\v2\x16.sessions.MessageProtoR\bmessages\"5\n" +
	"\x14CountMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"7\n" +
	"\x16CompactMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x1e\n" +
	"\fBoolResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"%\n" +
	"\rCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"+\n" +
	"\x0fCompactResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\x05R\aremoved2\xed\x05\n" +
	"\x0fSessionsService\x12G\n" +
	"\rCreateSession\x12\x1e.sessions.CreateSessionRequest\x1a\x16.sessions.SessionProto\x12A\n" +
	"\n" +
	"GetSession\x12\x1b.sessions.GetSessionRequest\x1a\x16.sessions.SessionProto\x12M\n" +
	"\fListSessions\x12\x1d.sessions.ListSessionsRequest\x1a\x1e.sessions.ListSessionsResponse\x12G\n" +
	"\rDeleteSession\x12\x1e.sessions.DeleteSessionRequest\x1a\x16.sessions.BoolResponse\x12G\n" +
	"\rCommitSession\x12\x1e.sessions.CommitSessionRequest\x1a\x16.sessions.BoolResponse\x12A\n" +
	"\n" +
	"AddMessage\x12\x1b.sessions.AddMessageRequest\x1a\x16.sessions.BoolResponse\x12A\n" +
	"\n" +
	"GetMessage\x12\x1b.sessions.GetMessageRequest\x1a\x16.sessions.MessageProto\x12M\n" +
	"\fListMessages\x12\x1d.sessions.ListMessagesRequest\x1a\x1e.sessions.ListMessagesResponse\x12H\n" +
	"\rCountMessages\x12\x1e.sessions.CountMessagesRequest\x1a\x17.sessions.CountResponse\x12N\n" +
	"\x0fCompactMessages\x12 .sessions.CompactMessagesRequest\x1a\x19.sessions.CompactResponseB>Z<github.com/mwantia/forge-sdk/pkg/plugins/grpc/sessions/protob\x06proto3"

var (
	file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescOnce sync.Once
	file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescData []byte
)

func file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescGZIP() []byte {
	file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescOnce.Do(func() {
		file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDesc), len(file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDesc)))
	})
	return file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDescData
}

var file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pkg_plugins_grpc_sessions_proto_sessions_proto_goTypes = []any{
	(*SessionProto)(nil),           // 0: sessions.SessionProto
	(*MessageProto)(nil),           // 1: sessions.MessageProto
	(*ToolCallProto)(nil),          // 2: sessions.ToolCallProto
	(*CreateSessionRequest)(nil),   // 3: sessions.CreateSessionRequest
	(*GetSessionRequest)(nil),      // 4: sessions.GetSessionRequest
	(*ListSessionsRequest)(nil),    // 5: sessions.ListSessionsRequest
	(*ListSessionsResponse)(nil),   // 6: sessions.ListSessionsResponse
	(*DeleteSessionRequest)(nil),   // 7: sessions.DeleteSessionRequest
	(*CommitSessionRequest)(nil),   // 8: sessions.CommitSessionRequest
	(*AddMessageRequest)(nil),      // 9: sessions.AddMessageRequest
	(*GetMessageRequest)(nil),      // 10: sessions.GetMessageRequest
	(*ListMessagesRequest)(nil),    // 11: sessions.ListMessagesRequest
	(*ListMessagesResponse)(nil),   // 12: sessions.ListMessagesResponse
	(*CountMessagesRequest)(nil),   // 13: sessions.CountMessagesRequest
	(*CompactMessagesRequest)(nil), // 14: sessions.CompactMessagesRequest
	(*BoolResponse)(nil),           // 15: sessions.BoolResponse
	(*CountResponse)(nil),          // 16: sessions.CountResponse
	(*CompactResponse)(nil),        // 17: sessions.CompactResponse
	(*structpb.Struct)(nil),        // 18: google.protobuf.Struct
}
var file_pkg_plugins_grpc_sessions_proto_sessions_proto_depIdxs = []int32{
	18, // 0: sessions.SessionProto.metadata:type_name -> google.protobuf.Struct
	2,  // 1: sessions.MessageProto.tool_calls:type_name -> sessions.ToolCallProto
	18, // 2: sessions.ToolCallProto.arguments:type_name -> google.protobuf.Struct
	18, // 3: sessions.CreateSessionRequest.metadata:type_name -> google.protobuf.Struct
	0,  // 4: sessions.ListSessionsResponse.sessions:type_name -> sessions.SessionProto
	1,  // 5: sessions.AddMessageRequest.message:type_name -> sessions.MessageProto
	1,  // 6: sessions.ListMessagesResponse.messages:type_name -> sessions.MessageProto
	3,  // 7: sessions.SessionsService.CreateSession:input_type -> sessions.CreateSessionRequest
	4,  // 8: sessions.SessionsService.GetSession:input_type -> sessions.GetSessionRequest
	5,  // 9: sessions.SessionsService.ListSessions:input_type -> sessions.ListSessionsRequest
	7,  // 10: sessions.SessionsService.DeleteSession:input_type -> sessions.DeleteSessionRequest
	8,  // 11: sessions.SessionsService.CommitSession:input_type -> sessions.CommitSessionRequest
	9,  // 12: sessions.SessionsService.AddMessage:input_type -> sessions.AddMessageRequest
	10, // 13: sessions.SessionsService.GetMessage:input_type -> sessions.GetMessageRequest
	11, // 14: sessions.SessionsService.ListMessages:input_type -> sessions.ListMessagesRequest
	13, // 15: sessions.SessionsService.CountMessages:input_type -> sessions.CountMessagesRequest
	14, // 16: sessions.SessionsService.CompactMessages:input_type -> sessions.CompactMessagesRequest
	0,  // 17: sessions.SessionsService.CreateSession:output_type -> sessions.SessionProto
	0,  // 18: sessions.SessionsService.GetSession:output_type -> sessions.SessionProto
	6,  // 19: sessions.SessionsService.ListSessions:output_type -> sessions.ListSessionsResponse
	15, // 20: sessions.SessionsService.DeleteSession:output_type -> sessions.BoolResponse
	15, // 21: sessions.SessionsService.CommitSession:output_type -> sessions.BoolResponse
	15, // 22: sessions.SessionsService.AddMessage:output_type -> sessions.BoolResponse
	1,  // 23: sessions.SessionsService.GetMessage:output_type -> sessions.MessageProto
	12, // 24: sessions.SessionsService.ListMessages:output_type -> sessions.ListMessagesResponse
	16, // 25: sessions.SessionsService.CountMessages:output_type -> sessions.CountResponse
	17, // 26: sessions.SessionsService.CompactMessages:output_type -> sessions.CompactResponse
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_plugins_grpc_sessions_proto_sessions_proto_init() }
func file_pkg_plugins_grpc_sessions_proto_sessions_proto_init() {
	if File_pkg_plugins_grpc_sessions_proto_sessions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDesc), len(file_pkg_plugins_grpc_sessions_proto_sessions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugins_grpc_sessions_proto_sessions_proto_goTypes,
		DependencyIndexes: file_pkg_plugins_grpc_sessions_proto_sessions_proto_depIdxs,
		MessageInfos:      file_pkg_plugins_grpc_sessions_proto_sessions_proto_msgTypes,
	}.Build()
	File_pkg_plugins_grpc_sessions_proto_sessions_proto = out.File
	file_pkg_plugins_grpc_sessions_proto_sessions_proto_goTypes = nil
	file_pkg_plugins_grpc_sessions_proto_sessions_proto_depIdxs = nil
}
