version: '3'

env:
    CGO_ENABLED: '0'
    GOOS: linux

dotenv: ['.env']

tasks:
    default:
        desc: List all available tasks
        cmds:
        - task --list
        silent: true

    setup:
        desc: Download and tidy Go module dependencies
        cmds:
        - go mod download
        - go mod tidy

    proto:
        desc: Generate gRPC code from all proto definitions
        cmds:
        - |
            protoc --go_out=. --go-grpc_out=. \
                --go_opt=paths=source_relative \
                --go-grpc_opt=paths=source_relative \
                pkg/plugins/grpc/driver/proto/common.proto \
                pkg/plugins/grpc/driver/proto/driver.proto
        - |
            protoc --go_out=. --go-grpc_out=. \
                --go_opt=paths=source_relative \
                --go-grpc_opt=paths=source_relative \
                pkg/plugins/grpc/tools/proto/tools.proto
        - |
            protoc --go_out=. --go-grpc_out=. \
                --go_opt=paths=source_relative \
                --go-grpc_opt=paths=source_relative \
                pkg/plugins/grpc/provider/proto/provider.proto
        - |
            protoc --go_out=. --go-grpc_out=. \
                --go_opt=paths=source_relative \
                --go-grpc_opt=paths=source_relative \
                pkg/plugins/grpc/memory/proto/memory.proto
        - |
            protoc --go_out=. --go-grpc_out=. \
                --go_opt=paths=source_relative \
                --go-grpc_opt=paths=source_relative \
                pkg/plugins/grpc/sessions/proto/sessions.proto
        - |
            protoc --go_out=. --go-grpc_out=. \
                --go_opt=paths=source_relative \
                --go-grpc_opt=paths=source_relative \
                pkg/plugins/grpc/channel/proto/channel.proto
        - |
            protoc --go_out=. --go-grpc_out=. \
                --go_opt=paths=source_relative \
                --go-grpc_opt=paths=source_relative \
                pkg/plugins/grpc/sandbox/proto/sandbox.proto