// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/plugins/grpc/memory/proto/memory.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescGZIP(), []int{0}
}

func (x *StoreRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StoreRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StoreRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescGZIP(), []int{1}
}

func (x *StoreResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Filter        *structpb.Struct       `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RetrieveRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RetrieveRequest) GetFilter() *structpb.Struct {
	if x != nil {
		return x.Filter
	}
	return nil
}

type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*MemoryResultProto   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveResponse) GetResults() []*MemoryResultProto {
	if x != nil {
		return x.Results
	}
	return nil
}

type MemoryResultProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryResultProto) Reset() {
	*x = MemoryResultProto{}
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryResultProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryResultProto) ProtoMessage() {}

func (x *MemoryResultProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryResultProto.ProtoReflect.Descriptor instead.
func (*MemoryResultProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryResultProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryResultProto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryResultProto) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MemoryResultProto) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_pkg_plugins_grpc_memory_proto_memory_proto protoreflect.FileDescriptor

const file_pkg_plugins_grpc_memory_proto_memory_proto_rawDesc = "" +
	"\n" +
	"*pkg/plugins/grpc/memory/proto/memory.proto\x12\x06memory\x1a\x1cgoogle/protobuf/struct.proto\"{\n" +
	"\fStoreRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\"\x1f\n" +
	"\rStoreResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8c\x01\n" +
	"\x0fRetrieveRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12/\n" +
	"\x06filter\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06filter\"G\n" +
	"\x10RetrieveResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.memory.MemoryResultProtoR\aresults\"\x88\x01\n" +
	"\x11MemoryResultProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata2\x84\x01\n" +
	"\rMemoryService\x124\n" +
	"\x05Store\x12\x14.memory.StoreRequest\x1a\x15.memory.StoreResponse\x12=\n" +
	"\bRetrieve\x12\x17.memory.RetrieveRequest\x1a\x18.memory.RetrieveResponseB<Z:github.com/mwantia/forge-sdk/pkg/plugins/grpc/memory/protob\x06proto3"

var (
	file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescOnce sync.Once
	file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescData []byte
)

func file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescGZIP() []byte {
	file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescOnce.Do(func() {
		file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugins_grpc_memory_proto_memory_proto_rawDesc), len(file_pkg_plugins_grpc_memory_proto_memory_proto_rawDesc)))
	})
	return file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescData
}

var file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_plugins_grpc_memory_proto_memory_proto_goTypes = []any{
	(*StoreRequest)(nil),      // 0: memory.StoreRequest
	(*StoreResponse)(nil),     // 1: memory.StoreResponse
	(*RetrieveRequest)(nil),   // 2: memory.RetrieveRequest
	(*RetrieveResponse)(nil),  // 3: memory.RetrieveResponse
	(*MemoryResultProto)(nil), // 4: memory.MemoryResultProto
	(*structpb.Struct)(nil),   // 5: google.protobuf.Struct
}
var file_pkg_plugins_grpc_memory_proto_memory_proto_depIdxs = []int32{
	5, // 0: memory.StoreRequest.metadata:type_name -> google.protobuf.Struct
	5, // 1: memory.RetrieveRequest.filter:type_name -> google.protobuf.Struct
	4, // 2: memory.RetrieveResponse.results:type_name -> memory.MemoryResultProto
	5, // 3: memory.MemoryResultProto.metadata:type_name -> google.protobuf.Struct
	0, // 4: memory.MemoryService.Store:input_type -> memory.StoreRequest
	2, // 5: memory.MemoryService.Retrieve:input_type -> memory.RetrieveRequest
	1, // 6: memory.MemoryService.Store:output_type -> memory.StoreResponse
	3, // 7: memory.MemoryService.Retrieve:output_type -> memory.RetrieveResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_plugins_grpc_memory_proto_memory_proto_init() }
func file_pkg_plugins_grpc_memory_proto_memory_proto_init() {
	if File_pkg_plugins_grpc_memory_proto_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugins_grpc_memory_proto_memory_proto_rawDesc), len(file_pkg_plugins_grpc_memory_proto_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugins_grpc_memory_proto_memory_proto_goTypes,
		DependencyIndexes: file_pkg_plugins_grpc_memory_proto_memory_proto_depIdxs,
		MessageInfos:      file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes,
	}.Build()
	File_pkg_plugins_grpc_memory_proto_memory_proto = out.File
	file_pkg_plugins_grpc_memory_proto_memory_proto_goTypes = nil
	file_pkg_plugins_grpc_memory_proto_memory_proto_depIdxs = nil
}
