// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/plugins/grpc/provider/proto/provider.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*MessageProto        `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Temperature   float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Tools         []*ToolDefProto        `protobuf:"bytes,5,rep,name=tools,proto3" json:"tools,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetMessages() []*MessageProto {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ChatRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ChatRequest) GetTools() []*ToolDefProto {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ChatRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TokenUsageProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	TotalTokens   int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	InputCost     float64                `protobuf:"fixed64,4,opt,name=input_cost,json=inputCost,proto3" json:"input_cost,omitempty"`
	OutputCost    float64                `protobuf:"fixed64,5,opt,name=output_cost,json=outputCost,proto3" json:"output_cost,omitempty"`
	TotalCost     float64                `protobuf:"fixed64,6,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenUsageProto) Reset() {
	*x = TokenUsageProto{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsageProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsageProto) ProtoMessage() {}

func (x *TokenUsageProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsageProto.ProtoReflect.Descriptor instead.
func (*TokenUsageProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{1}
}

func (x *TokenUsageProto) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *TokenUsageProto) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *TokenUsageProto) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *TokenUsageProto) GetInputCost() float64 {
	if x != nil {
		return x.InputCost
	}
	return 0
}

func (x *TokenUsageProto) GetOutputCost() float64 {
	if x != nil {
		return x.OutputCost
	}
	return 0
}

func (x *TokenUsageProto) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

type ChatChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Delta         string                 `protobuf:"bytes,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	ToolCalls     []*ToolCallProto       `protobuf:"bytes,5,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	Model         string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	Usage         *TokenUsageProto       `protobuf:"bytes,7,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatChunk) Reset() {
	*x = ChatChunk{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatChunk) ProtoMessage() {}

func (x *ChatChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatChunk.ProtoReflect.Descriptor instead.
func (*ChatChunk) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{2}
}

func (x *ChatChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatChunk) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *ChatChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ChatChunk) GetToolCalls() []*ToolCallProto {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *ChatChunk) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatChunk) GetUsage() *TokenUsageProto {
	if x != nil {
		return x.Usage
	}
	return nil
}

type MessageProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ToolCalls     []*ToolCallProto       `protobuf:"bytes,3,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageProto) Reset() {
	*x = MessageProto{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageProto) ProtoMessage() {}

func (x *MessageProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageProto.ProtoReflect.Descriptor instead.
func (*MessageProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{3}
}

func (x *MessageProto) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MessageProto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageProto) GetToolCalls() []*ToolCallProto {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

type ToolDefProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    *structpb.Struct       `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefProto) Reset() {
	*x = ToolDefProto{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefProto) ProtoMessage() {}

func (x *ToolDefProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefProto.ProtoReflect.Descriptor instead.
func (*ToolDefProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{4}
}

func (x *ToolDefProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefProto) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ToolCallProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     *structpb.Struct       `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallProto) Reset() {
	*x = ToolCallProto{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallProto) ProtoMessage() {}

func (x *ToolCallProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallProto.ProtoReflect.Descriptor instead.
func (*ToolCallProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCallProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCallProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCallProto) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{6}
}

func (x *EmbedRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbedRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*EmbeddingProto      `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{7}
}

func (x *EmbedResponse) GetEmbeddings() []*EmbeddingProto {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

type EmbeddingProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingProto) Reset() {
	*x = EmbeddingProto{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingProto) ProtoMessage() {}

func (x *EmbeddingProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingProto.ProtoReflect.Descriptor instead.
func (*EmbeddingProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{8}
}

func (x *EmbeddingProto) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{9}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelProto          `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{10}
}

func (x *ListModelsResponse) GetModels() []*ModelProto {
	if x != nil {
		return x.Models
	}
	return nil
}

type CreateModelRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BaseModel      string                 `protobuf:"bytes,2,opt,name=base_model,json=baseModel,proto3" json:"base_model,omitempty"`
	PromptTemplate string                 `protobuf:"bytes,3,opt,name=prompt_template,json=promptTemplate,proto3" json:"prompt_template,omitempty"`
	System         string                 `protobuf:"bytes,4,opt,name=system,proto3" json:"system,omitempty"`
	Parameters     map[string]string      `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateModelRequest) Reset() {
	*x = CreateModelRequest{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelRequest) ProtoMessage() {}

func (x *CreateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelRequest.ProtoReflect.Descriptor instead.
func (*CreateModelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{11}
}

func (x *CreateModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateModelRequest) GetBaseModel() string {
	if x != nil {
		return x.BaseModel
	}
	return ""
}

func (x *CreateModelRequest) GetPromptTemplate() string {
	if x != nil {
		return x.PromptTemplate
	}
	return ""
}

func (x *CreateModelRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *CreateModelRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type CreateModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *ModelProto            `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelResponse) Reset() {
	*x = CreateModelResponse{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelResponse) ProtoMessage() {}

func (x *CreateModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelResponse.ProtoReflect.Descriptor instead.
func (*CreateModelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{12}
}

func (x *CreateModelResponse) GetModel() *ModelProto {
	if x != nil {
		return x.Model
	}
	return nil
}

type GetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelRequest) Reset() {
	*x = GetModelRequest{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelRequest) ProtoMessage() {}

func (x *GetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelRequest.ProtoReflect.Descriptor instead.
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{13}
}

func (x *GetModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *ModelProto            `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelResponse) Reset() {
	*x = GetModelResponse{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelResponse) ProtoMessage() {}

func (x *GetModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelResponse.ProtoReflect.Descriptor instead.
func (*GetModelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{14}
}

func (x *GetModelResponse) GetModel() *ModelProto {
	if x != nil {
		return x.Model
	}
	return nil
}

type DeleteModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelRequest) Reset() {
	*x = DeleteModelRequest{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelRequest) ProtoMessage() {}

func (x *DeleteModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelRequest.ProtoReflect.Descriptor instead.
func (*DeleteModelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelResponse) Reset() {
	*x = DeleteModelResponse{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelResponse) ProtoMessage() {}

func (x *DeleteModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelResponse.ProtoReflect.Descriptor instead.
func (*DeleteModelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ModelProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dimension     int32                  `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelProto) Reset() {
	*x = ModelProto{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelProto) ProtoMessage() {}

func (x *ModelProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelProto.ProtoReflect.Descriptor instead.
func (*ModelProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{17}
}

func (x *ModelProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelProto) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *ModelProto) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_pkg_plugins_grpc_provider_proto_provider_proto protoreflect.FileDescriptor

const file_pkg_plugins_grpc_provider_proto_provider_proto_rawDesc = "" +
	"\n" +
	".pkg/plugins/grpc/provider/proto/provider.proto\x12\bprovider\x1a\x1cgoogle/protobuf/struct.proto\"\xc4\x02\n" +
	"\vChatRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x122\n" +
	"\bmessages\x18\x02 \x03(\v2\x16.provider.MessageProtoR\bmessages\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12,\n" +
	"\x05tools\x18\x05 \x03(\v2\x16.provider.ToolDefProtoR\x05tools\x12?\n" +
	"\bmetadata\x18\x06 \x03(\v2#.provider.ChatRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdb\x01\n" +
	"\x0fTokenUsageProto\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x05R\foutputTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\x12\x1d\n" +
	"\n" +
	"input_cost\x18\x04 \x01(\x01R\tinputCost\x12\x1f\n" +
	"\voutput_cost\x18\x05 \x01(\x01R\n" +
	"outputCost\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x06 \x01(\x01R\ttotalCost\"\xd8\x01\n" +
	"\tChatChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\tR\x05delta\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\x126\n" +
	"\n" +
	"tool_calls\x18\x05 \x03(\v2\x17.provider.ToolCallProtoR\ttoolCalls\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12/\n" +
	"\x05usage\x18\a \x01(\v2\x19.provider.TokenUsageProtoR\x05usage\"t\n" +
	"\fMessageProto\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x126\n" +
	"\n" +
	"tool_calls\x18\x03 \x03(\v2\x17.provider.ToolCallProtoR\ttoolCalls\"}\n" +
	"\fToolDefProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x127\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\"j\n" +
	"\rToolCallProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\targuments\x18\x03 \x01(\v2\x17.google.protobuf.StructR\targuments\">\n" +
	"\fEmbedRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"I\n" +
	"\rEmbedResponse\x128\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\x18.provider.EmbeddingProtoR\n" +
	"embeddings\"(\n" +
	"\x0eEmbeddingProto\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"\x13\n" +
	"\x11ListModelsRequest\"B\n" +
	"\x12ListModelsResponse\x12,\n" +
	"\x06models\x18\x01 \x03(\v2\x14.provider.ModelProtoR\x06models\"\x95\x02\n" +
	"\x12CreateModelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"base_model\x18\x02 \x01(\tR\tbaseModel\x12'\n" +
	"\x0fprompt_template\x18\x03 \x01(\tR\x0epromptTemplate\x12\x16\n" +
	"\x06system\x18\x04 \x01(\tR\x06system\x12L\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2,.provider.CreateModelRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x13CreateModelResponse\x12*\n" +
	"\x05model\x18\x01 \x01(\v2\x14.provider.ModelProtoR\x05model\"%\n" +
	"\x0fGetModelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\">\n" +
	"\x10GetModelResponse\x12*\n" +
	"\x05model\x18\x01 \x01(\v2\x14.provider.ModelProtoR\x05model\"(\n" +
	"\x12DeleteModelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x13DeleteModelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xbb\x01\n" +
	"\n" +
	"ModelProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\x05R\tdimension\x12>\n" +
	"\bmetadata\x18\x03 \x03(\v2\".provider.ModelProto.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa5\x03\n" +
	"\x0fProviderService\x124\n" +
	"\x04Chat\x12\x15.provider.ChatRequest\x1a\x13.provider.ChatChunk0\x01\x128\n" +
	"\x05Embed\x12\x16.provider.EmbedRequest\x1a\x17.provider.EmbedResponse\x12G\n" +
	"\n" +
	"ListModels\x12\x1b.provider.ListModelsRequest\x1a\x1c.provider.ListModelsResponse\x12J\n" +
	"\vCreateModel\x12\x1c.provider.CreateModelRequest\x1a\x1d.provider.CreateModelResponse\x12A\n" +
	"\bGetModel\x12\x19.provider.GetModelRequest\x1a\x1a.provider.GetModelResponse\x12J\n" +
	"\vDeleteModel\x12\x1c.provider.DeleteModelRequest\x1a\x1d.provider.DeleteModelResponseB>Z<github.com/mwantia/forge-sdk/pkg/plugins/grpc/provider/protob\x06proto3"

var (
	file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescOnce sync.Once
	file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescData []byte
)

func file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP() []byte {
	file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescOnce.Do(func() {
		file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugins_grpc_provider_proto_provider_proto_rawDesc), len(file_pkg_plugins_grpc_provider_proto_provider_proto_rawDesc)))
	})
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescData
}

var file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_pkg_plugins_grpc_provider_proto_provider_proto_goTypes = []any{
	(*ChatRequest)(nil),         // 0: provider.ChatRequest
	(*TokenUsageProto)(nil),     // 1: provider.TokenUsageProto
	(*ChatChunk)(nil),           // 2: provider.ChatChunk
	(*MessageProto)(nil),        // 3: provider.MessageProto
	(*ToolDefProto)(nil),        // 4: provider.ToolDefProto
	(*ToolCallProto)(nil),       // 5: provider.ToolCallProto
	(*EmbedRequest)(nil),        // 6: provider.EmbedRequest
	(*EmbedResponse)(nil),       // 7: provider.EmbedResponse
	(*EmbeddingProto)(nil),      // 8: provider.EmbeddingProto
	(*ListModelsRequest)(nil),   // 9: provider.ListModelsRequest
	(*ListModelsResponse)(nil),  // 10: provider.ListModelsResponse
	(*CreateModelRequest)(nil),  // 11: provider.CreateModelRequest
	(*CreateModelResponse)(nil), // 12: provider.CreateModelResponse
	(*GetModelRequest)(nil),     // 13: provider.GetModelRequest
	(*GetModelResponse)(nil),    // 14: provider.GetModelResponse
	(*DeleteModelRequest)(nil),  // 15: provider.DeleteModelRequest
	(*DeleteModelResponse)(nil), // 16: provider.DeleteModelResponse
	(*ModelProto)(nil),          // 17: provider.ModelProto
	nil,                         // 18: provider.ChatRequest.MetadataEntry
	nil,                         // 19: provider.CreateModelRequest.ParametersEntry
	nil,                         // 20: provider.ModelProto.MetadataEntry
	(*structpb.Struct)(nil),     // 21: google.protobuf.Struct
}
var file_pkg_plugins_grpc_provider_proto_provider_proto_depIdxs = []int32{
	3,  // 0: provider.ChatRequest.messages:type_name -> provider.MessageProto
	4,  // 1: provider.ChatRequest.tools:type_name -> provider.ToolDefProto
	18, // 2: provider.ChatRequest.metadata:type_name -> provider.ChatRequest.MetadataEntry
	5,  // 3: provider.ChatChunk.tool_calls:type_name -> provider.ToolCallProto
	1,  // 4: provider.ChatChunk.usage:type_name -> provider.TokenUsageProto
	5,  // 5: provider.MessageProto.tool_calls:type_name -> provider.ToolCallProto
	21, // 6: provider.ToolDefProto.parameters:type_name -> google.protobuf.Struct
	21, // 7: provider.ToolCallProto.arguments:type_name -> google.protobuf.Struct
	8,  // 8: provider.EmbedResponse.embeddings:type_name -> provider.EmbeddingProto
	17, // 9: provider.ListModelsResponse.models:type_name -> provider.ModelProto
	19, // 10: provider.CreateModelRequest.parameters:type_name -> provider.CreateModelRequest.ParametersEntry
	17, // 11: provider.CreateModelResponse.model:type_name -> provider.ModelProto
	17, // 12: provider.GetModelResponse.model:type_name -> provider.ModelProto
	20, // 13: provider.ModelProto.metadata:type_name -> provider.ModelProto.MetadataEntry
	0,  // 14: provider.ProviderService.Chat:input_type -> provider.ChatRequest
	6,  // 15: provider.ProviderService.Embed:input_type -> provider.EmbedRequest
	9,  // 16: provider.ProviderService.ListModels:input_type -> provider.ListModelsRequest
	11, // 17: provider.ProviderService.CreateModel:input_type -> provider.CreateModelRequest
	13, // 18: provider.ProviderService.GetModel:input_type -> provider.GetModelRequest
	15, // 19: provider.ProviderService.DeleteModel:input_type -> provider.DeleteModelRequest
	2,  // 20: provider.ProviderService.Chat:output_type -> provider.ChatChunk
	7,  // 21: provider.ProviderService.Embed:output_type -> provider.EmbedResponse
	10, // 22: provider.ProviderService.ListModels:output_type -> provider.ListModelsResponse
	12, // 23: provider.ProviderService.CreateModel:output_type -> provider.CreateModelResponse
	14, // 24: provider.ProviderService.GetModel:output_type -> provider.GetModelResponse
	16, // 25: provider.ProviderService.DeleteModel:output_type -> provider.DeleteModelResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_pkg_plugins_grpc_provider_proto_provider_proto_init() }
func file_pkg_plugins_grpc_provider_proto_provider_proto_init() {
	if File_pkg_plugins_grpc_provider_proto_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugins_grpc_provider_proto_provider_proto_rawDesc), len(file_pkg_plugins_grpc_provider_proto_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugins_grpc_provider_proto_provider_proto_goTypes,
		DependencyIndexes: file_pkg_plugins_grpc_provider_proto_provider_proto_depIdxs,
		MessageInfos:      file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes,
	}.Build()
	File_pkg_plugins_grpc_provider_proto_provider_proto = out.File
	file_pkg_plugins_grpc_provider_proto_provider_proto_goTypes = nil
	file_pkg_plugins_grpc_provider_proto_provider_proto_depIdxs = nil
}
