// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/plugins/grpc/driver/proto/common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PluginInfo describes plugin metadata at the driver level.
type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_pkg_plugins_grpc_driver_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// DriverCapabilities describes what a driver supports.
type DriverCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []string               `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	Provider      *ProviderCapabilities  `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Resource      *ResourceCapabilities  `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Channel       *ChannelCapabilities   `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	Tools         *ToolsCapabilities     `protobuf:"bytes,5,opt,name=tools,proto3" json:"tools,omitempty"`
	Sandbox       *SandboxCapabilities   `protobuf:"bytes,6,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverCapabilities) Reset() {
	*x = DriverCapabilities{}
	mi := &file_pkg_plugins_grpc_driver_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverCapabilities) ProtoMessage() {}

func (x *DriverCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverCapabilities.ProtoReflect.Descriptor instead.
func (*DriverCapabilities) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *DriverCapabilities) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *DriverCapabilities) GetProvider() *ProviderCapabilities {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *DriverCapabilities) GetResource() *ResourceCapabilities {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *DriverCapabilities) GetChannel() *ChannelCapabilities {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *DriverCapabilities) GetTools() *ToolsCapabilities {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *DriverCapabilities) GetSandbox() *SandboxCapabilities {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type ProviderCapabilities struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SupportsStreaming bool                   `protobuf:"varint,1,opt,name=supports_streaming,json=supportsStreaming,proto3" json:"supports_streaming,omitempty"`
	SupportsVision    bool                   `protobuf:"varint,2,opt,name=supports_vision,json=supportsVision,proto3" json:"supports_vision,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProviderCapabilities) Reset() {
	*x = ProviderCapabilities{}
	mi := &file_pkg_plugins_grpc_driver_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCapabilities) ProtoMessage() {}

func (x *ProviderCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCapabilities.ProtoReflect.Descriptor instead.
func (*ProviderCapabilities) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderCapabilities) GetSupportsStreaming() bool {
	if x != nil {
		return x.SupportsStreaming
	}
	return false
}

func (x *ProviderCapabilities) GetSupportsVision() bool {
	if x != nil {
		return x.SupportsVision
	}
	return false
}

type ResourceCapabilities struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SupportsVectorSearch bool                   `protobuf:"varint,1,opt,name=supports_vector_search,json=supportsVectorSearch,proto3" json:"supports_vector_search,omitempty"`
	MaxContextSize       int32                  `protobuf:"varint,2,opt,name=max_context_size,json=maxContextSize,proto3" json:"max_context_size,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResourceCapabilities) Reset() {
	*x = ResourceCapabilities{}
	mi := &file_pkg_plugins_grpc_driver_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceCapabilities) ProtoMessage() {}

func (x *ResourceCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceCapabilities.ProtoReflect.Descriptor instead.
func (*ResourceCapabilities) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceCapabilities) GetSupportsVectorSearch() bool {
	if x != nil {
		return x.SupportsVectorSearch
	}
	return false
}

func (x *ResourceCapabilities) GetMaxContextSize() int32 {
	if x != nil {
		return x.MaxContextSize
	}
	return 0
}

type ChannelCapabilities struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SupportsDirectMessages bool                   `protobuf:"varint,1,opt,name=supports_direct_messages,json=supportsDirectMessages,proto3" json:"supports_direct_messages,omitempty"`
	SupportsThreads        bool                   `protobuf:"varint,2,opt,name=supports_threads,json=supportsThreads,proto3" json:"supports_threads,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ChannelCapabilities) Reset() {
	*x = ChannelCapabilities{}
	mi := &file_pkg_plugins_grpc_driver_proto_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCapabilities) ProtoMessage() {}

func (x *ChannelCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCapabilities.ProtoReflect.Descriptor instead.
func (*ChannelCapabilities) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_common_proto_rawDescGZIP(), []int{4}
}

func (x *ChannelCapabilities) GetSupportsDirectMessages() bool {
	if x != nil {
		return x.SupportsDirectMessages
	}
	return false
}

func (x *ChannelCapabilities) GetSupportsThreads() bool {
	if x != nil {
		return x.SupportsThreads
	}
	return false
}

type ToolsCapabilities struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SupportsAsyncExecution bool                   `protobuf:"varint,1,opt,name=supports_async_execution,json=supportsAsyncExecution,proto3" json:"supports_async_execution,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ToolsCapabilities) Reset() {
	*x = ToolsCapabilities{}
	mi := &file_pkg_plugins_grpc_driver_proto_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolsCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolsCapabilities) ProtoMessage() {}

func (x *ToolsCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolsCapabilities.ProtoReflect.Descriptor instead.
func (*ToolsCapabilities) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_common_proto_rawDescGZIP(), []int{5}
}

func (x *ToolsCapabilities) GetSupportsAsyncExecution() bool {
	if x != nil {
		return x.SupportsAsyncExecution
	}
	return false
}

type SandboxCapabilities struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IsolationMode      string                 `protobuf:"bytes,1,opt,name=isolation_mode,json=isolationMode,proto3" json:"isolation_mode,omitempty"`
	SupportsStreaming  bool                   `protobuf:"varint,2,opt,name=supports_streaming,json=supportsStreaming,proto3" json:"supports_streaming,omitempty"`
	SupportsFilesystem bool                   `protobuf:"varint,3,opt,name=supports_filesystem,json=supportsFilesystem,proto3" json:"supports_filesystem,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SandboxCapabilities) Reset() {
	*x = SandboxCapabilities{}
	mi := &file_pkg_plugins_grpc_driver_proto_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCapabilities) ProtoMessage() {}

func (x *SandboxCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCapabilities.ProtoReflect.Descriptor instead.
func (*SandboxCapabilities) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_common_proto_rawDescGZIP(), []int{6}
}

func (x *SandboxCapabilities) GetIsolationMode() string {
	if x != nil {
		return x.IsolationMode
	}
	return ""
}

func (x *SandboxCapabilities) GetSupportsStreaming() bool {
	if x != nil {
		return x.SupportsStreaming
	}
	return false
}

func (x *SandboxCapabilities) GetSupportsFilesystem() bool {
	if x != nil {
		return x.SupportsFilesystem
	}
	return false
}

var File_pkg_plugins_grpc_driver_proto_common_proto protoreflect.FileDescriptor

const file_pkg_plugins_grpc_driver_proto_common_proto_rawDesc = "" +
	"\n" +
	"*pkg/plugins/grpc/driver/proto/common.proto\x12\x06driver\"R\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xbd\x02\n" +
	"\x12DriverCapabilities\x12\x14\n" +
	"\x05types\x18\x01 \x03(\tR\x05types\x128\n" +
	"\bprovider\x18\x02 \x01(\v2\x1c.driver.ProviderCapabilitiesR\bprovider\x128\n" +
	"\bresource\x18\x03 \x01(\v2\x1c.driver.ResourceCapabilitiesR\bresource\x125\n" +
	"\achannel\x18\x04 \x01(\v2\x1b.driver.ChannelCapabilitiesR\achannel\x12/\n" +
	"\x05tools\x18\x05 \x01(\v2\x19.driver.ToolsCapabilitiesR\x05tools\x125\n" +
	"\asandbox\x18\x06 \x01(\v2\x1b.driver.SandboxCapabilitiesR\asandbox\"n\n" +
	"\x14ProviderCapabilities\x12-\n" +
	"\x12supports_streaming\x18\x01 \x01(\bR\x11supportsStreaming\x12'\n" +
	"\x0fsupports_vision\x18\x02 \x01(\bR\x0esupportsVision\"v\n" +
	"\x14ResourceCapabilities\x124\n" +
	"\x16supports_vector_search\x18\x01 \x01(\bR\x14supportsVectorSearch\x12(\n" +
	"\x10max_context_size\x18\x02 \x01(\x05R\x0emaxContextSize\"z\n" +
	"\x13ChannelCapabilities\x128\n" +
	"\x18supports_direct_messages\x18\x01 \x01(\bR\x16supportsDirectMessages\x12)\n" +
	"\x10supports_threads\x18\x02 \x01(\bR\x0fsupportsThreads\"M\n" +
	"\x11ToolsCapabilities\x128\n" +
	"\x18supports_async_execution\x18\x01 \x01(\bR\x16supportsAsyncExecution\"\x9c\x01\n" +
	"\x13SandboxCapabilities\x12%\n" +
	"\x0eisolation_mode\x18\x01 \x01(\tR\risolationMode\x12-\n" +
	"\x12supports_streaming\x18\x02 \x01(\bR\x11supportsStreaming\x12/\n" +
	"\x13supports_filesystem\x18\x03 \x01(\bR\x12supportsFilesystemB<Z:github.com/mwantia/forge-sdk/pkg/plugins/grpc/driver/protob\x06proto3"

var (
	file_pkg_plugins_grpc_driver_proto_common_proto_rawDescOnce sync.Once
	file_pkg_plugins_grpc_driver_proto_common_proto_rawDescData []byte
)

func file_pkg_plugins_grpc_driver_proto_common_proto_rawDescGZIP() []byte {
	file_pkg_plugins_grpc_driver_proto_common_proto_rawDescOnce.Do(func() {
		file_pkg_plugins_grpc_driver_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugins_grpc_driver_proto_common_proto_rawDesc), len(file_pkg_plugins_grpc_driver_proto_common_proto_rawDesc)))
	})
	return file_pkg_plugins_grpc_driver_proto_common_proto_rawDescData
}

var file_pkg_plugins_grpc_driver_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_plugins_grpc_driver_proto_common_proto_goTypes = []any{
	(*PluginInfo)(nil),           // 0: driver.PluginInfo
	(*DriverCapabilities)(nil),   // 1: driver.DriverCapabilities
	(*ProviderCapabilities)(nil), // 2: driver.ProviderCapabilities
	(*ResourceCapabilities)(nil), // 3: driver.ResourceCapabilities
	(*ChannelCapabilities)(nil),  // 4: driver.ChannelCapabilities
	(*ToolsCapabilities)(nil),    // 5: driver.ToolsCapabilities
	(*SandboxCapabilities)(nil),  // 6: driver.SandboxCapabilities
}
var file_pkg_plugins_grpc_driver_proto_common_proto_depIdxs = []int32{
	2, // 0: driver.DriverCapabilities.provider:type_name -> driver.ProviderCapabilities
	3, // 1: driver.DriverCapabilities.resource:type_name -> driver.ResourceCapabilities
	4, // 2: driver.DriverCapabilities.channel:type_name -> driver.ChannelCapabilities
	5, // 3: driver.DriverCapabilities.tools:type_name -> driver.ToolsCapabilities
	6, // 4: driver.DriverCapabilities.sandbox:type_name -> driver.SandboxCapabilities
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_plugins_grpc_driver_proto_common_proto_init() }
func file_pkg_plugins_grpc_driver_proto_common_proto_init() {
	if File_pkg_plugins_grpc_driver_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugins_grpc_driver_proto_common_proto_rawDesc), len(file_pkg_plugins_grpc_driver_proto_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_plugins_grpc_driver_proto_common_proto_goTypes,
		DependencyIndexes: file_pkg_plugins_grpc_driver_proto_common_proto_depIdxs,
		MessageInfos:      file_pkg_plugins_grpc_driver_proto_common_proto_msgTypes,
	}.Build()
	File_pkg_plugins_grpc_driver_proto_common_proto = out.File
	file_pkg_plugins_grpc_driver_proto_common_proto_goTypes = nil
	file_pkg_plugins_grpc_driver_proto_common_proto_depIdxs = nil
}
