// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/plugins/grpc/driver/proto/driver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPluginInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginInfoRequest) Reset() {
	*x = GetPluginInfoRequest{}
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginInfoRequest) ProtoMessage() {}

func (x *GetPluginInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPluginInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescGZIP(), []int{0}
}

type GetPluginInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *PluginInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginInfoResponse) Reset() {
	*x = GetPluginInfoResponse{}
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginInfoResponse) ProtoMessage() {}

func (x *GetPluginInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPluginInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescGZIP(), []int{1}
}

func (x *GetPluginInfoResponse) GetInfo() *PluginInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescGZIP(), []int{2}
}

type ProbeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResponse) Reset() {
	*x = ProbeResponse{}
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResponse) ProtoMessage() {}

func (x *ProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResponse.ProtoReflect.Descriptor instead.
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescGZIP(), []int{3}
}

func (x *ProbeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescGZIP(), []int{4}
}

type CapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  *DriverCapabilities    `protobuf:"bytes,1,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescGZIP(), []int{5}
}

func (x *CapabilitiesResponse) GetCapabilities() *DriverCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescGZIP(), []int{6}
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescGZIP(), []int{7}
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescGZIP(), []int{8}
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescGZIP(), []int{9}
}

type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *structpb.Struct       `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescGZIP(), []int{11}
}

type GetPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginRequest) Reset() {
	*x = GetPluginRequest{}
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginRequest) ProtoMessage() {}

func (x *GetPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginRequest.ProtoReflect.Descriptor instead.
func (*GetPluginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescGZIP(), []int{12}
}

type GetPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginResponse) Reset() {
	*x = GetPluginResponse{}
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginResponse) ProtoMessage() {}

func (x *GetPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginResponse.ProtoReflect.Descriptor instead.
func (*GetPluginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescGZIP(), []int{13}
}

func (x *GetPluginResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

var File_pkg_plugins_grpc_driver_proto_driver_proto protoreflect.FileDescriptor

const file_pkg_plugins_grpc_driver_proto_driver_proto_rawDesc = "" +
	"\n" +
	"*pkg/plugins/grpc/driver/proto/driver.proto\x12\x06driver\x1a\x1cgoogle/protobuf/struct.proto\x1a*pkg/plugins/grpc/driver/proto/common.proto\"\x16\n" +
	"\x14GetPluginInfoRequest\"?\n" +
	"\x15GetPluginInfoResponse\x12&\n" +
	"\x04info\x18\x01 \x01(\v2\x12.driver.PluginInfoR\x04info\"\x0e\n" +
	"\fProbeRequest\"\x1f\n" +
	"\rProbeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x15\n" +
	"\x13CapabilitiesRequest\"V\n" +
	"\x14CapabilitiesResponse\x12>\n" +
	"\fcapabilities\x18\x01 \x01(\v2\x1a.driver.DriverCapabilitiesR\fcapabilities\"\r\n" +
	"\vOpenRequest\"\x0e\n" +
	"\fOpenResponse\"\x0e\n" +
	"\fCloseRequest\"\x0f\n" +
	"\rCloseResponse\"@\n" +
	"\rConfigRequest\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06config\"\x10\n" +
	"\x0eConfigResponse\"\x12\n" +
	"\x10GetPluginRequest\"1\n" +
	"\x11GetPluginResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable2\xd0\x06\n" +
	"\rDriverService\x12L\n" +
	"\rGetPluginInfo\x12\x1c.driver.GetPluginInfoRequest\x1a\x1d.driver.GetPluginInfoResponse\x12:\n" +
	"\vProbePlugin\x12\x14.driver.ProbeRequest\x1a\x15.driver.ProbeResponse\x12L\n" +
	"\x0fGetCapabilities\x12\x1b.driver.CapabilitiesRequest\x1a\x1c.driver.CapabilitiesResponse\x127\n" +
	"\n" +
	"OpenDriver\x12\x13.driver.OpenRequest\x1a\x14.driver.OpenResponse\x12:\n" +
	"\vCloseDriver\x12\x14.driver.CloseRequest\x1a\x15.driver.CloseResponse\x12=\n" +
	"\fConfigDriver\x12\x15.driver.ConfigRequest\x1a\x16.driver.ConfigResponse\x12H\n" +
	"\x11GetProviderPlugin\x12\x18.driver.GetPluginRequest\x1a\x19.driver.GetPluginResponse\x12F\n" +
	"\x0fGetMemoryPlugin\x12\x18.driver.GetPluginRequest\x1a\x19.driver.GetPluginResponse\x12H\n" +
	"\x11GetSessionsPlugin\x12\x18.driver.GetPluginRequest\x1a\x19.driver.GetPluginResponse\x12G\n" +
	"\x10GetChannelPlugin\x12\x18.driver.GetPluginRequest\x1a\x19.driver.GetPluginResponse\x12E\n" +
	"\x0eGetToolsPlugin\x12\x18.driver.GetPluginRequest\x1a\x19.driver.GetPluginResponse\x12G\n" +
	"\x10GetSandboxPlugin\x12\x18.driver.GetPluginRequest\x1a\x19.driver.GetPluginResponseB<Z:github.com/mwantia/forge-sdk/pkg/plugins/grpc/driver/protob\x06proto3"

var (
	file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescOnce sync.Once
	file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescData []byte
)

func file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescGZIP() []byte {
	file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescOnce.Do(func() {
		file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugins_grpc_driver_proto_driver_proto_rawDesc), len(file_pkg_plugins_grpc_driver_proto_driver_proto_rawDesc)))
	})
	return file_pkg_plugins_grpc_driver_proto_driver_proto_rawDescData
}

var file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_plugins_grpc_driver_proto_driver_proto_goTypes = []any{
	(*GetPluginInfoRequest)(nil),  // 0: driver.GetPluginInfoRequest
	(*GetPluginInfoResponse)(nil), // 1: driver.GetPluginInfoResponse
	(*ProbeRequest)(nil),          // 2: driver.ProbeRequest
	(*ProbeResponse)(nil),         // 3: driver.ProbeResponse
	(*CapabilitiesRequest)(nil),   // 4: driver.CapabilitiesRequest
	(*CapabilitiesResponse)(nil),  // 5: driver.CapabilitiesResponse
	(*OpenRequest)(nil),           // 6: driver.OpenRequest
	(*OpenResponse)(nil),          // 7: driver.OpenResponse
	(*CloseRequest)(nil),          // 8: driver.CloseRequest
	(*CloseResponse)(nil),         // 9: driver.CloseResponse
	(*ConfigRequest)(nil),         // 10: driver.ConfigRequest
	(*ConfigResponse)(nil),        // 11: driver.ConfigResponse
	(*GetPluginRequest)(nil),      // 12: driver.GetPluginRequest
	(*GetPluginResponse)(nil),     // 13: driver.GetPluginResponse
	(*PluginInfo)(nil),            // 14: driver.PluginInfo
	(*DriverCapabilities)(nil),    // 15: driver.DriverCapabilities
	(*structpb.Struct)(nil),       // 16: google.protobuf.Struct
}
var file_pkg_plugins_grpc_driver_proto_driver_proto_depIdxs = []int32{
	14, // 0: driver.GetPluginInfoResponse.info:type_name -> driver.PluginInfo
	15, // 1: driver.CapabilitiesResponse.capabilities:type_name -> driver.DriverCapabilities
	16, // 2: driver.ConfigRequest.config:type_name -> google.protobuf.Struct
	0,  // 3: driver.DriverService.GetPluginInfo:input_type -> driver.GetPluginInfoRequest
	2,  // 4: driver.DriverService.ProbePlugin:input_type -> driver.ProbeRequest
	4,  // 5: driver.DriverService.GetCapabilities:input_type -> driver.CapabilitiesRequest
	6,  // 6: driver.DriverService.OpenDriver:input_type -> driver.OpenRequest
	8,  // 7: driver.DriverService.CloseDriver:input_type -> driver.CloseRequest
	10, // 8: driver.DriverService.ConfigDriver:input_type -> driver.ConfigRequest
	12, // 9: driver.DriverService.GetProviderPlugin:input_type -> driver.GetPluginRequest
	12, // 10: driver.DriverService.GetMemoryPlugin:input_type -> driver.GetPluginRequest
	12, // 11: driver.DriverService.GetSessionsPlugin:input_type -> driver.GetPluginRequest
	12, // 12: driver.DriverService.GetChannelPlugin:input_type -> driver.GetPluginRequest
	12, // 13: driver.DriverService.GetToolsPlugin:input_type -> driver.GetPluginRequest
	12, // 14: driver.DriverService.GetSandboxPlugin:input_type -> driver.GetPluginRequest
	1,  // 15: driver.DriverService.GetPluginInfo:output_type -> driver.GetPluginInfoResponse
	3,  // 16: driver.DriverService.ProbePlugin:output_type -> driver.ProbeResponse
	5,  // 17: driver.DriverService.GetCapabilities:output_type -> driver.CapabilitiesResponse
	7,  // 18: driver.DriverService.OpenDriver:output_type -> driver.OpenResponse
	9,  // 19: driver.DriverService.CloseDriver:output_type -> driver.CloseResponse
	11, // 20: driver.DriverService.ConfigDriver:output_type -> driver.ConfigResponse
	13, // 21: driver.DriverService.GetProviderPlugin:output_type -> driver.GetPluginResponse
	13, // 22: driver.DriverService.GetMemoryPlugin:output_type -> driver.GetPluginResponse
	13, // 23: driver.DriverService.GetSessionsPlugin:output_type -> driver.GetPluginResponse
	13, // 24: driver.DriverService.GetChannelPlugin:output_type -> driver.GetPluginResponse
	13, // 25: driver.DriverService.GetToolsPlugin:output_type -> driver.GetPluginResponse
	13, // 26: driver.DriverService.GetSandboxPlugin:output_type -> driver.GetPluginResponse
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_plugins_grpc_driver_proto_driver_proto_init() }
func file_pkg_plugins_grpc_driver_proto_driver_proto_init() {
	if File_pkg_plugins_grpc_driver_proto_driver_proto != nil {
		return
	}
	file_pkg_plugins_grpc_driver_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugins_grpc_driver_proto_driver_proto_rawDesc), len(file_pkg_plugins_grpc_driver_proto_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugins_grpc_driver_proto_driver_proto_goTypes,
		DependencyIndexes: file_pkg_plugins_grpc_driver_proto_driver_proto_depIdxs,
		MessageInfos:      file_pkg_plugins_grpc_driver_proto_driver_proto_msgTypes,
	}.Build()
	File_pkg_plugins_grpc_driver_proto_driver_proto = out.File
	file_pkg_plugins_grpc_driver_proto_driver_proto_goTypes = nil
	file_pkg_plugins_grpc_driver_proto_driver_proto_depIdxs = nil
}
