// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/plugins/grpc/sandbox/proto/sandbox.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SandboxPathRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Writable      bool                   `protobuf:"varint,2,opt,name=writable,proto3" json:"writable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxPathRule) Reset() {
	*x = SandboxPathRule{}
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxPathRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxPathRule) ProtoMessage() {}

func (x *SandboxPathRule) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxPathRule.ProtoReflect.Descriptor instead.
func (*SandboxPathRule) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *SandboxPathRule) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SandboxPathRule) GetWritable() bool {
	if x != nil {
		return x.Writable
	}
	return false
}

type SandboxSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AllowedHostPaths []*SandboxPathRule     `protobuf:"bytes,2,rep,name=allowed_host_paths,json=allowedHostPaths,proto3" json:"allowed_host_paths,omitempty"`
	WorkDir          string                 `protobuf:"bytes,3,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	Env              map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata         *structpb.Struct       `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SandboxSpec) Reset() {
	*x = SandboxSpec{}
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxSpec) ProtoMessage() {}

func (x *SandboxSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxSpec.ProtoReflect.Descriptor instead.
func (*SandboxSpec) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *SandboxSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SandboxSpec) GetAllowedHostPaths() []*SandboxPathRule {
	if x != nil {
		return x.AllowedHostPaths
	}
	return nil
}

func (x *SandboxSpec) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *SandboxSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *SandboxSpec) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *SandboxSpec           `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSandboxRequest) GetSpec() *SandboxSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CreateSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Driver        string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxResponse) Reset() {
	*x = CreateSandboxResponse{}
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxResponse) ProtoMessage() {}

func (x *CreateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxResponse.ProtoReflect.Descriptor instead.
func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSandboxResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateSandboxResponse) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

type DestroySandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySandboxRequest) Reset() {
	*x = DestroySandboxRequest{}
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySandboxRequest) ProtoMessage() {}

func (x *DestroySandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySandboxRequest.ProtoReflect.Descriptor instead.
func (*DestroySandboxRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *DestroySandboxRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DestroySandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySandboxResponse) Reset() {
	*x = DestroySandboxResponse{}
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySandboxResponse) ProtoMessage() {}

func (x *DestroySandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySandboxResponse.ProtoReflect.Descriptor instead.
func (*DestroySandboxResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescGZIP(), []int{5}
}

type CopyInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HostSrc       string                 `protobuf:"bytes,2,opt,name=host_src,json=hostSrc,proto3" json:"host_src,omitempty"`
	SandboxDst    string                 `protobuf:"bytes,3,opt,name=sandbox_dst,json=sandboxDst,proto3" json:"sandbox_dst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyInRequest) Reset() {
	*x = CopyInRequest{}
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyInRequest) ProtoMessage() {}

func (x *CopyInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyInRequest.ProtoReflect.Descriptor instead.
func (*CopyInRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescGZIP(), []int{6}
}

func (x *CopyInRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CopyInRequest) GetHostSrc() string {
	if x != nil {
		return x.HostSrc
	}
	return ""
}

func (x *CopyInRequest) GetSandboxDst() string {
	if x != nil {
		return x.SandboxDst
	}
	return ""
}

type CopyInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyInResponse) Reset() {
	*x = CopyInResponse{}
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyInResponse) ProtoMessage() {}

func (x *CopyInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyInResponse.ProtoReflect.Descriptor instead.
func (*CopyInResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescGZIP(), []int{7}
}

type CopyOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SandboxSrc    string                 `protobuf:"bytes,2,opt,name=sandbox_src,json=sandboxSrc,proto3" json:"sandbox_src,omitempty"`
	HostDst       string                 `protobuf:"bytes,3,opt,name=host_dst,json=hostDst,proto3" json:"host_dst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyOutRequest) Reset() {
	*x = CopyOutRequest{}
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyOutRequest) ProtoMessage() {}

func (x *CopyOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyOutRequest.ProtoReflect.Descriptor instead.
func (*CopyOutRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescGZIP(), []int{8}
}

func (x *CopyOutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CopyOutRequest) GetSandboxSrc() string {
	if x != nil {
		return x.SandboxSrc
	}
	return ""
}

func (x *CopyOutRequest) GetHostDst() string {
	if x != nil {
		return x.HostDst
	}
	return ""
}

type CopyOutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyOutResponse) Reset() {
	*x = CopyOutResponse{}
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyOutResponse) ProtoMessage() {}

func (x *CopyOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyOutResponse.ProtoReflect.Descriptor instead.
func (*CopyOutResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescGZIP(), []int{9}
}

type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SandboxId      string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args           []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ExecuteRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ExecuteChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"` // "stdout" or "stderr"
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // set on final chunk
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	IsError       bool                   `protobuf:"varint,5,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteChunk) Reset() {
	*x = ExecuteChunk{}
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteChunk) ProtoMessage() {}

func (x *ExecuteChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteChunk.ProtoReflect.Descriptor instead.
func (*ExecuteChunk) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescGZIP(), []int{11}
}

func (x *ExecuteChunk) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *ExecuteChunk) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ExecuteChunk) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ExecuteChunk) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescGZIP(), []int{12}
}

func (x *StatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	IsDir         bool                   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Mode          string                 `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTime       string                 `protobuf:"bytes,6,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescGZIP(), []int{13}
}

func (x *StatResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StatResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *StatResponse) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *StatResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StatResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *StatResponse) GetModTime() string {
	if x != nil {
		return x.ModTime
	}
	return ""
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescGZIP(), []int{14}
}

func (x *ReadFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescGZIP(), []int{15}
}

func (x *ReadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pkg_plugins_grpc_sandbox_proto_sandbox_proto protoreflect.FileDescriptor

const file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDesc = "" +
	"\n" +
	",pkg/plugins/grpc/sandbox/proto/sandbox.proto\x12\asandbox\x1a\x1cgoogle/protobuf/struct.proto\"A\n" +
	"\x0fSandboxPathRule\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\bwritable\x18\x02 \x01(\bR\bwritable\"\xa2\x02\n" +
	"\vSandboxSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12F\n" +
	"\x12allowed_host_paths\x18\x02 \x03(\v2\x18.sandbox.SandboxPathRuleR\x10allowedHostPaths\x12\x19\n" +
	"\bwork_dir\x18\x03 \x01(\tR\aworkDir\x12/\n" +
	"\x03env\x18\x04 \x03(\v2\x1d.sandbox.SandboxSpec.EnvEntryR\x03env\x123\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x14CreateSandboxRequest\x12(\n" +
	"\x04spec\x18\x01 \x01(\v2\x14.sandbox.SandboxSpecR\x04spec\"?\n" +
	"\x15CreateSandboxResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\"'\n" +
	"\x15DestroySandboxRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DestroySandboxResponse\"[\n" +
	"\rCopyInRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bhost_src\x18\x02 \x01(\tR\ahostSrc\x12\x1f\n" +
	"\vsandbox_dst\x18\x03 \x01(\tR\n" +
	"sandboxDst\"\x10\n" +
	"\x0eCopyInResponse\"\\\n" +
	"\x0eCopyOutRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vsandbox_src\x18\x02 \x01(\tR\n" +
	"sandboxSrc\x12\x19\n" +
	"\bhost_dst\x18\x03 \x01(\tR\ahostDst\"\x11\n" +
	"\x0fCopyOutResponse\"\xf2\x01\n" +
	"\x0eExecuteRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x122\n" +
	"\x03env\x18\x04 \x03(\v2 .sandbox.ExecuteRequest.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x01\n" +
	"\fExecuteChunk\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\x12\x19\n" +
	"\bis_error\x18\x05 \x01(\bR\aisError\"1\n" +
	"\vStatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x94\x01\n" +
	"\fStatResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode\x12\x19\n" +
	"\bmod_time\x18\x06 \x01(\tR\amodTime\"5\n" +
	"\x0fReadFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"&\n" +
	"\x10ReadFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xdf\x03\n" +
	"\x0eSandboxService\x12N\n" +
	"\rCreateSandbox\x12\x1d.sandbox.CreateSandboxRequest\x1a\x1e.sandbox.CreateSandboxResponse\x12Q\n" +
	"\x0eDestroySandbox\x12\x1e.sandbox.DestroySandboxRequest\x1a\x1f.sandbox.DestroySandboxResponse\x129\n" +
	"\x06CopyIn\x12\x16.sandbox.CopyInRequest\x1a\x17.sandbox.CopyInResponse\x12<\n" +
	"\aCopyOut\x12\x17.sandbox.CopyOutRequest\x1a\x18.sandbox.CopyOutResponse\x12;\n" +
	"\aExecute\x12\x17.sandbox.ExecuteRequest\x1a\x15.sandbox.ExecuteChunk0\x01\x123\n" +
	"\x04Stat\x12\x14.sandbox.StatRequest\x1a\x15.sandbox.StatResponse\x12?\n" +
	"\bReadFile\x12\x18.sandbox.ReadFileRequest\x1a\x19.sandbox.ReadFileResponseB=Z;github.com/mwantia/forge-sdk/pkg/plugins/grpc/sandbox/protob\x06proto3"

var (
	file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescOnce sync.Once
	file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescData []byte
)

func file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescGZIP() []byte {
	file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescOnce.Do(func() {
		file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDesc), len(file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDesc)))
	})
	return file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDescData
}

var file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_goTypes = []any{
	(*SandboxPathRule)(nil),        // 0: sandbox.SandboxPathRule
	(*SandboxSpec)(nil),            // 1: sandbox.SandboxSpec
	(*CreateSandboxRequest)(nil),   // 2: sandbox.CreateSandboxRequest
	(*CreateSandboxResponse)(nil),  // 3: sandbox.CreateSandboxResponse
	(*DestroySandboxRequest)(nil),  // 4: sandbox.DestroySandboxRequest
	(*DestroySandboxResponse)(nil), // 5: sandbox.DestroySandboxResponse
	(*CopyInRequest)(nil),          // 6: sandbox.CopyInRequest
	(*CopyInResponse)(nil),         // 7: sandbox.CopyInResponse
	(*CopyOutRequest)(nil),         // 8: sandbox.CopyOutRequest
	(*CopyOutResponse)(nil),        // 9: sandbox.CopyOutResponse
	(*ExecuteRequest)(nil),         // 10: sandbox.ExecuteRequest
	(*ExecuteChunk)(nil),           // 11: sandbox.ExecuteChunk
	(*StatRequest)(nil),            // 12: sandbox.StatRequest
	(*StatResponse)(nil),           // 13: sandbox.StatResponse
	(*ReadFileRequest)(nil),        // 14: sandbox.ReadFileRequest
	(*ReadFileResponse)(nil),       // 15: sandbox.ReadFileResponse
	nil,                            // 16: sandbox.SandboxSpec.EnvEntry
	nil,                            // 17: sandbox.ExecuteRequest.EnvEntry
	(*structpb.Struct)(nil),        // 18: google.protobuf.Struct
}
var file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_depIdxs = []int32{
	0,  // 0: sandbox.SandboxSpec.allowed_host_paths:type_name -> sandbox.SandboxPathRule
	16, // 1: sandbox.SandboxSpec.env:type_name -> sandbox.SandboxSpec.EnvEntry
	18, // 2: sandbox.SandboxSpec.metadata:type_name -> google.protobuf.Struct
	1,  // 3: sandbox.CreateSandboxRequest.spec:type_name -> sandbox.SandboxSpec
	17, // 4: sandbox.ExecuteRequest.env:type_name -> sandbox.ExecuteRequest.EnvEntry
	2,  // 5: sandbox.SandboxService.CreateSandbox:input_type -> sandbox.CreateSandboxRequest
	4,  // 6: sandbox.SandboxService.DestroySandbox:input_type -> sandbox.DestroySandboxRequest
	6,  // 7: sandbox.SandboxService.CopyIn:input_type -> sandbox.CopyInRequest
	8,  // 8: sandbox.SandboxService.CopyOut:input_type -> sandbox.CopyOutRequest
	10, // 9: sandbox.SandboxService.Execute:input_type -> sandbox.ExecuteRequest
	12, // 10: sandbox.SandboxService.Stat:input_type -> sandbox.StatRequest
	14, // 11: sandbox.SandboxService.ReadFile:input_type -> sandbox.ReadFileRequest
	3,  // 12: sandbox.SandboxService.CreateSandbox:output_type -> sandbox.CreateSandboxResponse
	5,  // 13: sandbox.SandboxService.DestroySandbox:output_type -> sandbox.DestroySandboxResponse
	7,  // 14: sandbox.SandboxService.CopyIn:output_type -> sandbox.CopyInResponse
	9,  // 15: sandbox.SandboxService.CopyOut:output_type -> sandbox.CopyOutResponse
	11, // 16: sandbox.SandboxService.Execute:output_type -> sandbox.ExecuteChunk
	13, // 17: sandbox.SandboxService.Stat:output_type -> sandbox.StatResponse
	15, // 18: sandbox.SandboxService.ReadFile:output_type -> sandbox.ReadFileResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_init() }
func file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_init() {
	if File_pkg_plugins_grpc_sandbox_proto_sandbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDesc), len(file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_goTypes,
		DependencyIndexes: file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_depIdxs,
		MessageInfos:      file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_msgTypes,
	}.Build()
	File_pkg_plugins_grpc_sandbox_proto_sandbox_proto = out.File
	file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_goTypes = nil
	file_pkg_plugins_grpc_sandbox_proto_sandbox_proto_depIdxs = nil
}
