// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/plugins/grpc/channel/proto/channel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_pkg_plugins_grpc_channel_proto_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_channel_proto_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_channel_proto_channel_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SendRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_pkg_plugins_grpc_channel_proto_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_channel_proto_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_channel_proto_channel_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type ReceiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveRequest) Reset() {
	*x = ReceiveRequest{}
	mi := &file_pkg_plugins_grpc_channel_proto_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRequest) ProtoMessage() {}

func (x *ReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_channel_proto_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRequest.ProtoReflect.Descriptor instead.
func (*ReceiveRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_channel_proto_channel_proto_rawDescGZIP(), []int{2}
}

func (x *ReceiveRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type MessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_pkg_plugins_grpc_channel_proto_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_channel_proto_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_channel_proto_channel_proto_rawDescGZIP(), []int{3}
}

func (x *MessageEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageEvent) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *MessageEvent) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *MessageEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_pkg_plugins_grpc_channel_proto_channel_proto protoreflect.FileDescriptor

const file_pkg_plugins_grpc_channel_proto_channel_proto_rawDesc = "" +
	"\n" +
	",pkg/plugins/grpc/channel/proto/channel.proto\x12\achannel\"\xc3\x01\n" +
	"\vSendRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12>\n" +
	"\bmetadata\x18\x03 \x03(\v2\".channel.SendRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\fSendResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"/\n" +
	"\x0eReceiveRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"\xf2\x01\n" +
	"\fMessageEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12?\n" +
	"\bmetadata\x18\x05 \x03(\v2#.channel.MessageEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x82\x01\n" +
	"\x0eChannelService\x123\n" +
	"\x04Send\x12\x14.channel.SendRequest\x1a\x15.channel.SendResponse\x12;\n" +
	"\aReceive\x12\x17.channel.ReceiveRequest\x1a\x15.channel.MessageEvent0\x01B=Z;github.com/mwantia/forge-sdk/pkg/plugins/grpc/channel/protob\x06proto3"

var (
	file_pkg_plugins_grpc_channel_proto_channel_proto_rawDescOnce sync.Once
	file_pkg_plugins_grpc_channel_proto_channel_proto_rawDescData []byte
)

func file_pkg_plugins_grpc_channel_proto_channel_proto_rawDescGZIP() []byte {
	file_pkg_plugins_grpc_channel_proto_channel_proto_rawDescOnce.Do(func() {
		file_pkg_plugins_grpc_channel_proto_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugins_grpc_channel_proto_channel_proto_rawDesc), len(file_pkg_plugins_grpc_channel_proto_channel_proto_rawDesc)))
	})
	return file_pkg_plugins_grpc_channel_proto_channel_proto_rawDescData
}

var file_pkg_plugins_grpc_channel_proto_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_plugins_grpc_channel_proto_channel_proto_goTypes = []any{
	(*SendRequest)(nil),    // 0: channel.SendRequest
	(*SendResponse)(nil),   // 1: channel.SendResponse
	(*ReceiveRequest)(nil), // 2: channel.ReceiveRequest
	(*MessageEvent)(nil),   // 3: channel.MessageEvent
	nil,                    // 4: channel.SendRequest.MetadataEntry
	nil,                    // 5: channel.MessageEvent.MetadataEntry
}
var file_pkg_plugins_grpc_channel_proto_channel_proto_depIdxs = []int32{
	4, // 0: channel.SendRequest.metadata:type_name -> channel.SendRequest.MetadataEntry
	5, // 1: channel.MessageEvent.metadata:type_name -> channel.MessageEvent.MetadataEntry
	0, // 2: channel.ChannelService.Send:input_type -> channel.SendRequest
	2, // 3: channel.ChannelService.Receive:input_type -> channel.ReceiveRequest
	1, // 4: channel.ChannelService.Send:output_type -> channel.SendResponse
	3, // 5: channel.ChannelService.Receive:output_type -> channel.MessageEvent
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_plugins_grpc_channel_proto_channel_proto_init() }
func file_pkg_plugins_grpc_channel_proto_channel_proto_init() {
	if File_pkg_plugins_grpc_channel_proto_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugins_grpc_channel_proto_channel_proto_rawDesc), len(file_pkg_plugins_grpc_channel_proto_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugins_grpc_channel_proto_channel_proto_goTypes,
		DependencyIndexes: file_pkg_plugins_grpc_channel_proto_channel_proto_depIdxs,
		MessageInfos:      file_pkg_plugins_grpc_channel_proto_channel_proto_msgTypes,
	}.Build()
	File_pkg_plugins_grpc_channel_proto_channel_proto = out.File
	file_pkg_plugins_grpc_channel_proto_channel_proto_goTypes = nil
	file_pkg_plugins_grpc_channel_proto_channel_proto_depIdxs = nil
}
